# Generated by Django 3.2.13 on 2022-05-02 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('done', 'done'), ('to do', 'to do'), ('in review', 'in review'), ('cancelled', 'cancelled'), ('blocked', 'blocked')], default='open', max_length=11)),
                ('category', models.CharField(choices=[('bug', 'bug'), ('epic', 'epic'), ('improvement', 'improvement'), ('new feature', 'new feature'), ('story', 'story'), ('task', 'task')], default='development', max_length=11)),
                ('due_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
